name: Publish results

on:
  workflow_run:
    workflows: ["Build results"]
    types:
      - completed


jobs:
  publish_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "results-workflow"
      - name: publish_results
        run: asv publish
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: results-html
          file_pattern: html/*.* results/*.*
          commit_user_name: 'Github actions bot'
